-- APP模块 - 应用测试会话表
CREATE TABLE IF NOT EXISTS `t_app_test_session` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `session_id` VARCHAR(128) UNIQUE NOT NULL COMMENT '会话ID',
  `app_id` BIGINT NOT NULL COMMENT 'AI应用ID',
  `session_name` VARCHAR(128) DEFAULT '测试会话' COMMENT '会话名称',
  `model_id` BIGINT COMMENT '使用的模型ID',
  `user_id` BIGINT COMMENT '测试用户ID',
  `session_config` JSON COMMENT '会话配置（变量、参数等）',
  `session_state` VARCHAR(16) DEFAULT 'ACTIVE' COMMENT '会话状态: ACTIVE/FINISHED/EXPIRED',
  `message_count` INT DEFAULT 0 COMMENT '消息总数',
  `last_message_time` BIGINT COMMENT '最后消息时间（毫秒时间戳）',
  `start_time` BIGINT COMMENT '会话开始时间（毫秒时间戳）',
  `end_time` BIGINT COMMENT '会话结束时间（毫秒时间戳）',
  `total_tokens` INT DEFAULT 0 COMMENT '总消耗Token数',
  `total_cost` DECIMAL(10,6) DEFAULT 0 COMMENT '总费用',
  `is_deleted` TINYINT DEFAULT 0 COMMENT '逻辑删除',
  `created_by` VARCHAR(64) COMMENT '创建者',
  `updated_by` VARCHAR(64) COMMENT '更新者', 
  `created_at` BIGINT COMMENT '创建时间（毫秒时间戳）',
  `updated_at` BIGINT COMMENT '更新时间（毫秒时间戳）',
  INDEX idx_session_id (`session_id`),
  INDEX idx_app_id (`app_id`),
  INDEX idx_user_id (`user_id`),
  INDEX idx_model_id (`model_id`),
  INDEX idx_session_state (`session_state`),
  INDEX idx_last_message_time (`last_message_time`),
  INDEX idx_created_at (`created_at`)
) COMMENT 'AI应用测试会话表';