# 应用基本配置
spring:
  application:
    name: smartcs-web
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    cors:
      enabled: true
    mapping:
      /**:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
        allow-credentials: true
        max-age: 3600
  reactor:
    context-propagation: auto # Boot 3.2+ 原生支持

# MCP (Model Context Protocol) 配置
mcp:
  server:
    sql:
      enabled: true
      endpoint: "/mcp/sql"
      description: "SQL Query MCP Server"

# 日志配置
logging:
  level:
    root: info
    com:
      leyue:
        smartcs:
          config:
            feign: debug
#server:
#  servlet:
#    context-path: /smartcs
