-- 知识模块 - 内容表
CREATE TABLE IF NOT EXISTS `t_kb_content` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `knowledge_base_id` BIGINT NOT NULL COMMENT '所属知识库ID',
  `title` VARCHAR(256) NOT NULL COMMENT '标题',
  `content_type` VARCHAR(32) NOT NULL COMMENT 'document/audio/video',
  `file_url` VARCHAR(512) COMMENT '原始文件地址',
  `file_type` VARCHAR(256) COMMENT '文件扩展名',
  `text_extracted` TEXT COMMENT '提取后的原始文本',
  `status` VARCHAR(32) DEFAULT 'enabled' COMMENT 'enabled/disabled',
  `segment_mode` VARCHAR(32) DEFAULT 'general' COMMENT '分段模式 general/parent_child',
  `char_count` BIGINT DEFAULT 0 COMMENT '字符数',
  `recall_count` BIGINT DEFAULT 0 COMMENT '召回次数',
  `metadata` JSON COMMENT '元数据信息',
  `original_file_name` VARCHAR(256) COMMENT '原始文件名称',
  `file_size` BIGINT COMMENT '文件大小（字节）',
  `source` VARCHAR(64) COMMENT '来源 upload/api/import',
  `processing_time` BIGINT COMMENT '处理时间（毫秒）',
  `embedding_time` BIGINT COMMENT '向量化时间（毫秒）',
  `embedding_cost` BIGINT COMMENT '嵌入成本（tokens）',
  `average_chunk_length` INT COMMENT '平均段落长度',
  `chunk_count` INT COMMENT '段落数量',
  `processing_status` VARCHAR(32) COMMENT '处理状态 processing/success/failed',
  `processing_error_message` TEXT COMMENT '处理错误信息',
  `is_deleted` TINYINT DEFAULT 0 COMMENT '逻辑删除',
  `created_by` VARCHAR(64) COMMENT '创建者',
  `updated_by` VARCHAR(64) COMMENT '更新者',
  `created_at` BIGINT COMMENT '创建时间',
  `updated_at` BIGINT COMMENT '更新时间',
  INDEX idx_knowledge_base_id (`knowledge_base_id`),
  INDEX idx_content_type (`content_type`),
  INDEX idx_status (`status`),
  INDEX idx_processing_status (`processing_status`),
  INDEX idx_source (`source`)
) COMMENT '知识内容表';