-- 模型模块 - 任务表
CREATE TABLE IF NOT EXISTS `t_model_task` (
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    `task_id` VARCHAR(64) NOT NULL UNIQUE COMMENT '任务ID',
    `model_id` BIGINT NOT NULL COMMENT '模型ID',
    `task_type` VARCHAR(32) NOT NULL COMMENT '任务类型（INFERENCE/TRAINING/EVALUATION/FINE_TUNING）',
    `status` VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '任务状态（PENDING/RUNNING/COMPLETED/FAILED/CANCELLED）',
    `input_data` TEXT COMMENT '输入数据（JSON格式）',
    `output_data` TEXT COMMENT '输出数据（JSON格式）',
    `progress` INT DEFAULT 0 COMMENT '进度百分比（0-100）',
    `error_message` TEXT COMMENT '错误信息',
    `priority` INT DEFAULT 0 COMMENT '任务优先级',
    `started_at` BIGINT COMMENT '开始时间（毫秒时间戳）',
    `completed_at` BIGINT COMMENT '完成时间（毫秒时间戳）',
    `is_deleted` TINYINT DEFAULT 0 COMMENT '软删除标志',
    `created_by` VARCHAR(64) COMMENT '创建者',
    `updated_by` VARCHAR(64) COMMENT '更新者',
    `created_at` BIGINT COMMENT '创建时间（毫秒时间戳）',
    `updated_at` BIGINT COMMENT '更新时间（毫秒时间戳）',
    INDEX `idx_task_id` (`task_id`),
    INDEX `idx_model_id` (`model_id`),
    INDEX `idx_task_type` (`task_type`),
    INDEX `idx_status` (`status`),
    INDEX `idx_priority` (`priority`),
    INDEX `idx_created_at` (`created_at`),
    INDEX `idx_started_at` (`started_at`),
    INDEX `idx_completed_at` (`completed_at`),
    CONSTRAINT `fk_task_model_id` FOREIGN KEY (`model_id`) REFERENCES `t_model`(`id`)
) COMMENT '模型任务表';